Repository mercadopago/sdk-php, pull requests merged in 2023-09, with the labels that each got.

#439 Implementation Plans
  phpunit.xml
  src/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClient.php
  src/MercadoPago/Resources/PreApprovalPlan.php
  src/MercadoPago/Resources/PreApprovalPlan/AutoRecurring.php
  src/MercadoPago/Resources/PreApprovalPlan/FreeTrial.php
  src/MercadoPago/Resources/PreApprovalPlan/PaymentMethodsAllowed.php
  src/MercadoPago/Resources/PreApprovalPlanSearch.php
  tests/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClientITTest.php
  tests/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClientUnitTest.php
  tests/MercadoPago/Resources/Mocks/Response/PreApprovalPlan/preapprovalplan_base.json
  tests/MercadoPago/Resources/Mocks/Response/PreApprovalPlan/preapprovalplan_list.json
  tests/MercadoPago/Resources/Mocks/Response/PreApprovalPlan/preapprovalplan_update.json
Labels: Functionality

#441 Implementation identification type resource
  phpunit.xml
  src/MercadoPago/Client/IdentificationType/IdentificationTypeClient.php
  src/MercadoPago/Resources/IdentificationTypeResult.php
  tests/MercadoPago/Client/IdentificationType/IdentificationTypeClientITTest.php
  tests/MercadoPago/Client/IdentificationType/IdentificationTypeClientUnitTest.php
  tests/MercadoPago/Resources/Mocks/Response/IdentificationType/identification_type_list.json
Labels: Functionality

#443 Implementation Invoices
  src/MercadoPago/Client/Invoice/InvoiceClient.php
  src/MercadoPago/Resources/Invoice.php
  src/MercadoPago/Resources/Invoice/Payment.php
  src/MercadoPago/Resources/InvoiceSearch.php
  tests/MercadoPago/Client/Invoice/InvoiceClientUnitTest.php
  tests/MercadoPago/Resources/Mocks/Response/Invoice/invoice_base.json
  tests/MercadoPago/Resources/Mocks/Response/Invoice/invoice_list.json
Labels: Functionality

#444 Implementation User
  phpunit.xml
  src/MercadoPago/Client/Invoice/InvoiceClient.php
  src/MercadoPago/Client/User/UserClient.php
  src/MercadoPago/Resources/User.php
  src/MercadoPago/Resources/User/Address.php
  src/MercadoPago/Resources/User/AlternativePhone.php
  src/MercadoPago/Resources/User/BillData.php
  src/MercadoPago/Resources/User/BuyerReputation.php
  src/MercadoPago/Resources/User/BuyerReputationCancelled.php
  src/MercadoPago/Resources/User/BuyerReputationNotYetRated.php
  src/MercadoPago/Resources/User/BuyerReputationTransactions.php
  src/MercadoPago/Resources/User/BuyerReputationUnrated.php
  src/MercadoPago/Resources/User/Cancellations.php
  src/MercadoPago/Resources/User/Claims.php
  src/MercadoPago/Resources/User/Company.php
  src/MercadoPago/Resources/User/Context.php
  src/MercadoPago/Resources/User/Credit.php
  src/MercadoPago/Resources/User/DelayedHandlingTime.php
  src/MercadoPago/Resources/User/Metrics.php
  src/MercadoPago/Resources/User/Phone.php
  src/MercadoPago/Resources/User/Ratings.php
  src/MercadoPago/Resources/User/Sales.php
  src/MercadoPago/Resources/User/SellerReputation.php
  src/MercadoPago/Resources/User/Status.php
  src/MercadoPago/Resources/User/StatusBilling.php
  src/MercadoPago/Resources/User/StatusBuyImmediatePayment.php
  src/MercadoPago/Resources/User/StatusList.php
  src/MercadoPago/Resources/User/StatusShoppingCart.php
  src/MercadoPago/Resources/User/Transactions.php
  tests/MercadoPago/Client/User/UserClientITTest.php
  tests/MercadoPago/Client/User/UserClientUnitTest.php
  tests/MercadoPago/Resources/Mocks/Response/User/user_base.json
Labels: Functionality

#446 Improve autoloading
  composer.json
  composer.lock
  tests/MercadoPago/Client/Base/BaseClient.php
  tests/MercadoPago/Client/CardToken/CardTokenClientITTest.php
  tests/MercadoPago/Client/CardToken/CardTokenClientUnitTest.php
  tests/MercadoPago/Client/Customer/CustomerCardClientITTest.php
  tests/MercadoPago/Client/Customer/CustomerCardClientUnitTest.php
  tests/MercadoPago/Client/Customer/CustomerClientITTest.php
  tests/MercadoPago/Client/Customer/CustomerClientUnitTest.php
  tests/MercadoPago/Client/IdentificationType/IdentificationTypeClientITTest.php
  tests/MercadoPago/Client/IdentificationType/IdentificationTypeClientUnitTest.php
  tests/MercadoPago/Client/Invoice/InvoiceClientUnitTest.php
  tests/MercadoPago/Client/Payment/PaymentClientITTest.php
  tests/MercadoPago/Client/Payment/PaymentClientUnitTest.php
  tests/MercadoPago/Client/Payment/PaymentRefundClientITTest.php
  tests/MercadoPago/Client/Payment/PaymentRefundClientUnitTest.php
  tests/MercadoPago/Client/PaymentMethod/PaymentMethodClientITTest.php
  tests/MercadoPago/Client/PaymentMethod/PaymentMethodClientUnitTest.php
  tests/MercadoPago/Client/PreApproval/PreApprovalClientITTest.php
  tests/MercadoPago/Client/PreApproval/PreApprovalClientUnitTest.php
  tests/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClientITTest.php
  tests/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClientUnitTest.php
  tests/MercadoPago/Client/Preference/PreferenceClientITTest.php
  tests/MercadoPago/Client/Preference/PreferenceClientUnitTest.php
  tests/MercadoPago/Client/User/UserClientITTest.php
  tests/MercadoPago/Client/User/UserClientUnitTest.php
  tests/MercadoPago/MercadoPagoConfigTest.php
Labels: Refactor, Good Practices

#447 OAuth implementation
  src/MercadoPago/Client/OAuth/OAuthClient.php
  src/MercadoPago/Client/OAuth/OAuthCreateRequest.php
  src/MercadoPago/Client/OAuth/OAuthRefreshRequest.php
  src/MercadoPago/Resources/OAuth.php
  tests/MercadoPago/Client/OAuth/OAuthClientUnitTest.php
  tests/MercadoPago/Resources/Mocks/Response/OAuth/oauth_base.json
Labels: Functionality

#450 Add Idempotency Key
  src/MercadoPago/Client/MercadoPagoClient.php
Labels: Functionality

#452 Refactor request options
  src/MercadoPago/Client/CardToken/CardTokenClient.php
  src/MercadoPago/Client/Common/RequestOptions.php
  src/MercadoPago/Client/Customer/CustomerCardClient.php
  src/MercadoPago/Client/Customer/CustomerClient.php
  src/MercadoPago/Client/IdentificationType/IdentificationTypeClient.php
  src/MercadoPago/Client/Invoice/InvoiceClient.php
  src/MercadoPago/Client/MercadoPagoClient.php
  src/MercadoPago/Client/MerchantOrder/MerchantOrderClient.php
  src/MercadoPago/Client/OAuth/OAuthClient.php
  src/MercadoPago/Client/Payment/PaymentClient.php
  src/MercadoPago/Client/Payment/PaymentRefundClient.php
  src/MercadoPago/Client/PaymentMethod/PaymentMethodClient.php
  src/MercadoPago/Client/Point/PointClient.php
  src/MercadoPago/Client/PreApproval/PreApprovalClient.php
  src/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClient.php
  src/MercadoPago/Client/Preference/PreferenceClient.php
  src/MercadoPago/Client/User/UserClient.php
  tests/MercadoPago/Client/CardToken/CardTokenClientITTest.php
  tests/MercadoPago/Client/Customer/CustomerCardClientITTest.php
  tests/MercadoPago/Client/Customer/CustomerClientITTest.php
  tests/MercadoPago/Client/IdentificationType/IdentificationTypeClientITTest.php
  tests/MercadoPago/Client/MerchantOrder/MerchantOrderClientITTest.php
  tests/MercadoPago/Client/OAuth/OAuthClientUnitTest.php
  tests/MercadoPago/Client/Payment/PaymentClientITTest.php
  tests/MercadoPago/Client/Payment/PaymentRefundClientITTest.php
  tests/MercadoPago/Client/PaymentMethod/PaymentMethodClientITTest.php
  tests/MercadoPago/Client/Point/PointClientITTest.php
  tests/MercadoPago/Client/PreApproval/PreApprovalClientITTest.php
  tests/MercadoPago/Client/PreApprovalPlan/PreApprovalPlanClientITTest.php
  tests/MercadoPago/Client/Preference/PreferenceClientITTest.php
  tests/MercadoPago/Client/User/UserClientITTest.php
Labels: Refactor

#457 Fix resources mapping
  src/MercadoPago/Resources/Common/Address.php
  src/MercadoPago/Resources/CustomerCard.php
  src/MercadoPago/Resources/MerchantOrder.php
  src/MercadoPago/Resources/MerchantOrder/Collector.php
  src/MercadoPago/Resources/PaymentRefund.php
  src/MercadoPago/Resources/Preference.php
  src/MercadoPago/Resources/Preference/PaymentMethods.php
  tests/MercadoPago/Client/Integration/PreApprovalPlan/PreApprovalPlanClientITTest.php
Labels: Fix
